### PR TITLE
Export io Arbitraries

### PR DESCRIPTION
**Pull request by etorreborre**
I propose to be able to reuse the `LocalTemporaryArbitrary` definition in other projects.

### CODE REVIEW

**Comment by markhibberd** [comment]
You don't need to do this, they are already available, give me 5 and I will find an example of how to depend on it.

**Comment by markhibberd** [comment]
@etorreborre https://github.com/ambiata/notion/blob/master/project/depend.scala#L26

**Comment by etorreborre** [comment]
You mean that the tests jar for mundane-io is available?

**Comment by markhibberd** [comment]
Yep.

**Comment by markhibberd** [comment]
(part of trying to do this - https://github.com/ambiata/tooly)

**Comment by etorreborre** [comment]
Thanks I didn't realise that.

**Pull request closed without merging**
